import argparse

parser = argparse.ArgumentParser(description='Returning Rate Forecasting')
parser.add_argument('--n_input', type=list, default=[34, 4])
parser.add_argument('--n_embedding', type=int, default=128)
parser.add_argument('--n_embedding_hidden', type=int, default=64)
parser.add_argument('--n_output', type=int, default=25)
parser.add_argument('--seq_len', type=int, default=5)
parser.add_argument('--n_hiddens', type=list, default=[64, 64])
parser.add_argument('--trade_off_para', type=list, default=[0.495, 0.495, 0.01, 0.1])
parser.add_argument('--lr', type=float, default=8e-5)
######################LSTNet########################
parser.add_argument('--hidRNN', type=int, default=128, help='number of RNN hidden units')
parser.add_argument('--hidCNN', type=int, default=256, help='number of CNN hidden units')
parser.add_argument('--hidSkip', type=int, default=5)
parser.add_argument('--CNN_kernel', type=int, default=1, help='the kernel size of the CNN layers')
parser.add_argument('--skip', type=float, default=2)
parser.add_argument('--highway_window', type=int, default=2, help='The window size of the highway component')
parser.add_argument('--output_fun', type=str, default='sigmoid')
parser.add_argument('--seed', type=int, default=10)
####################################################
parser.add_argument('--data_dir', type=str, default='F:/partData/17')
parser.add_argument('--model_dir', type=str, default='_adarnn_4.pkl')
parser.add_argument('--dis_type', type=str, default='mmd')
parser.add_argument('--pre_epoch', type=int, default=20)
parser.add_argument('--device', type=str, default='cuda:0')
parser.add_argument('--num_cluster', type=int, default=2)
parser.add_argument('--layer', type=list, default=[3, 3])
parser.add_argument('--root', type=str, default='F:/partData/restored_5/')
parser.add_argument('--n_hidden', type=int, default=128)
parser.add_argument('--n_dim', type=int, default=34)
parser.add_argument('--epoch_acc', type=list, default=[])
parser.add_argument('--epoch_err', type=list, default=[])
parser.add_argument('--proportion', type=int, default=80)
args = parser.parse_args()
